server:
  port: 8680

spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:8889
  sleuth:
    sampler:
      percentage: 1.0

  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/    #注册 中心已经开启认证